### ISSUE TITLE
sheldon command not found the first time terminal start

### ISSUE THREAD

**Issue by yofriadi** [rossmacarthur/sheldon#100]
Sorry if this is a dumb question, but I don't want to source my zsh every first time I start my shell. how do you do this? thank you for this useful plugin manager!

**Comment by rossmacarthur** [comment]
@yofriadi could you elaborate on your question?

- When you open a new `zsh` shell (or `bash` or any other) it is normal for it not have anything extra.
- However, `zsh` itself will by default source `.zshrc`, (and `bash` will source `.bashrc` etc).
- Plugin managers like **sheldon** simply manage the downloading and automatic sourcing of plugins. So the main benefit is that you don't have to manually download, manage and put `source <directory>/xx.plugin.zsh` in your `.zshrc` for every plugin you want to have.

**Comment by yofriadi** [comment]
ah I get it working, I use asdf to manage my runtime language version (and cargo with rust) and it comes after `sheldon source` command and fixed the order of code now, thankss for the explain I get it now.
