### ISSUE TITLE
Not an issue - Just wanted to say thank you!

### ISSUE THREAD

**Issue by hurricanehrndz** [rossmacarthur/sheldon#113]
Hi just wanted to say my thanks! Great work!

**Comment by jltml** [comment]
I was just about to open a new issue to say this too! I've spent way too much time figuring out which plugin manager to use, but none of them seemed quite right... until Sheldon! I *love* how it uses a separate TOML config file and caching and — ok sorry I don't know why I'm so oddly enthusiastic about this but suffice it to say that this is pretty awesome (thanks!)
