### ISSUE TITLE
Installation issue with bash on MacOS

### ISSUE THREAD

**Issue by jason-o-matic** [rossmacarthur/sheldon#115]
I recently tried out sheldon on a Mojave box and ran into https://stackoverflow.com/questions/32596123/why-source-command-doesnt-work-with-process-substitution-in-bash-3-2 with using the current installation instructions. This could be why other tools use `eval`, but `source /dev/stdin <<<"$(cat <(sheldon source))"` worked for me to resolve the problem. Unfortunately it took a while to get to the bottom of the issue so I figured I'd post something in case anyone else searched for this like I did.

**Comment by rossmacarthur** [comment]
Thanks @jason-o-matic! I have updated the documentation. I have suggested `eval` as a replacement as it should work fine.
