### ISSUE TITLE
How to install only few plugins from oh my zsh?

### ISSUE THREAD

**Issue by kawpii** [rossmacarthur/sheldon#121]
I want to install only several plugins from OhMyZsh for performance reasons. Is there any way to do it? [Docs](https://sheldon.cli.rs/Examples.html#zsh-frameworks) only mention about adding whole OhMyZsh

I tried using remote like below
```
sheldon add yarnzsh --remote https://github.com/ohmyzsh/ohmyzsh/blob/master/plugins/yarn/yarn.plugin.zsh
```
but I am getting parsing error like below

> /home/username/.local/share/sheldon/downloads/github.com/ohmyzsh/ohmyzsh/blob/master/plugins/yarn/yarn.plugin.zsh:8: parse error near `\n'

**Comment by rossmacarthur** [comment]
The URL you are using returns the HTML webpage, so it is not valid shell code! You need to point to the actual source. Try something like this instead (note the `raw` in the URL):

```
sheldon add yarnzsh --remote https://github.com/ohmyzsh/ohmyzsh/raw/master/plugins/yarn/yarn.plugin.zsh
```

Another way of doing this is to add Oh My Zsh but only source the plugins you want. The following will select the `yarn` and `wd` plugins only.

```
sheldon add ohmyzsh --github ohmyzsh/ohmyzsh --dir plugins --use '{yarn,wd}/*.plugin.zsh'
```
