### ISSUE TITLE
Fish shell support

### ISSUE THREAD

**Issue by rossmacarthur** [rossmacarthur/sheldon#128]

**Comment by yonkeltron** [comment]
Just wanted to throw my support behind this feature, I'm a huge fan of Fish and would love to help test this out!

**Comment by rossmacarthur** [comment]
I have added experimental support for this in [8ba75aa](https://github.com/rossmacarthur/sheldon/commit/8ba75aa5be1911b2cba1e104e514299e1a361dab) which will be released in 0.7.2. Any help testing would be greatly appreciated

**Comment by yonkeltron** [comment]
Hey I'm all over this. Cloning the source now so I can take a crack at it. Let's see how it goes!

**Comment by rossmacarthur** [comment]
I've already noticed some problems 😅 and actually I wasn't sure about the design for this. It seems that fish plugins are generally well structured they have:
- conf.d
- completions
- functions

but I wasn't sure if the scripts should be sourced or if they should just be symlinked to the `~/.config/fish/` directories. `conf.d` generally needs to be executed _before_ `~/.config/fish/config.fish` so that would be an argument doing that.

**Comment by yonkeltron** [comment]
Happy to consult a bit more on this since there are two different approached, which are largely compatible. One is [Oh My FIsh](https://github.com/oh-my-fish/oh-my-fish) whereas the other is the lighter-weight [Fisher](https://github.com/jorgebucaran/fisher). Does this help? How can I help more?

**Comment by rossmacarthur** [comment]
Not implementing, please see [a804ff2](https://github.com/rossmacarthur/sheldon/commit/a804ff231e48a9c7e6895871da9ea926e017058d)·
