### ISSUE TITLE
Apple Silicon support

### ISSUE THREAD

**Issue by BK0STAR** [rossmacarthur/sheldon#130]
Hello

is there any plans for arm64 support in the future?

Thank you

**Comment by rossmacarthur** [comment]
Hi, are you getting a particular error? If you use the Homebrew or Cargo install it should work.

**Comment by chenrui333** [comment]
yeah, homebrew has already supported it 
https://github.com/Homebrew/homebrew-core/blob/9e5087b4e9d94cd1e369bd65f06ed905e7f20ef4/Formula/sheldon.rb#L10-L11

**Comment by rossmacarthur** [comment]
Closing in favour of #135
