### ISSUE TITLE
Default config directory is not as described in the documentation

### ISSUE THREAD

**Issue by kiriwalawren** [rossmacarthur/sheldon#134]
The [documentation](https://github.com/rossmacarthur/sheldon/blob/trunk/docs/src/Command-line-interface.md#options) states that the default path for the `--config-dir` is `<home>/.sheldon`. However, when I run the command this is not the case.
![image](https://user-images.githubusercontent.com/6665964/154380565-5d1c2bb1-8c31-4313-933c-93f690cb304d.png)
The default is `<home>/.config/sheldon` on my Kubuntu machine. However, the command works as expected when run inside a [Dev Container](https://code.visualstudio.com/docs/remote/containers).

Additionally, when I add the config file there, the download directory is also not defaulted to what is described in the the documentation. I am expecting repos to be cloned to `<home>/.sheldon/repos`. However, they are being cloned to `<home>/.local/share/sheldon/repos`:
![image](https://user-images.githubusercontent.com/6665964/154381126-13a7ad4f-fbff-4121-89c7-6140f9a9bb3a.png)

As a result the [instructions for configuring Oh My Zsh!](https://github.com/rossmacarthur/sheldon/blob/trunk/docs/src/Examples.md#ohmyzsh) do not work because the `ZSH` export value set is not where the `sheldon` is cloning `Oh My Zsh!`.

**Comment by rossmacarthur** [comment]
Thanks for the report, indeed the documentation should be updated. What is missing is that if you have any `XDG_*` environment variables set then the default values change to the following:

| Option                  | Environment variable   | Default                                                     |
| ----------------------- | ---------------------- | --------------------------------------------------------------- |
| `--config-dir <path>`   | `SHELDON_CONFIG_DIR`   | *default:* `XDG_CONFIG_HOME`        |
| `--data-dir <path>`     | `SHELDON_DATA_DIR`     | *default:* `XDG_DATA_HOME`          |

**Comment by kiriwalawren** [comment]
What happens if I have any `XDG_*` variable set but I do not have `XDG_CONFIG_HOME` or `XDG_DATA_HOME` set?

Edit: Because I just checked and I don't have those environment variables set. I imagine the documentation would need to be updated to explain that use case as well, right?

**Comment by rossmacarthur** [comment]
If any of the following [XDG][xdg] environment variables are set then the
default config and data directories will change.

- `XDG_CONFIG_HOME`
- `XDG_CACHE_HOME`
- `XDG_DATA_HOME`
- `XDG_DATA_DIRS`
- `XDG_CONFIG_DIRS`

| Environment variable | Default                   |
| -------------------- | ------------------------- |
| `SHELDON_CONFIG_DIR` | `XDG_CONFIG_HOME/sheldon` |
| `SHELDON_DATA_DIR`   | `XDG_DATA_HOME/sheldon`   |

The default values for the XDG environment variables are as specified in the
[XDG specification][xdg].

[xdg]: https://wiki.archlinux.org/title/XDG_Base_Directory

**Comment by rossmacarthur** [comment]
Possibly we should only check for `XDG_CONFIG_HOME` or `XDG_DATA_HOME`? I'm not actually sure what is the most appropriate action here. If we do then it won't be forward compatible if we ever wanted to use `XDG_CACHE_HOME` for example.

**Comment by rossmacarthur** [comment]
Fixed in fd6e3f375886538326cc0a8b6916fd6bb7a035c3

I'm going to close this issue, but please open another if you think the XDG behaviour should be different at all.

**Comment by sitiom** [comment]
> I'm going to close this issue, but please open another if you think the XDG behaviour should be different at all.

See https://github.com/rossmacarthur/sheldon/issues/136.
