### ISSUE TITLE
Release aarch64-apple-darwin binary

### ISSUE THREAD

**Issue by rossmacarthur** [rossmacarthur/sheldon#135]
Currently the Homebrew and Cargo install work fine on M1/M2 MacBooks but it would be nice to ship a Apple silicon binary from CI as well.

For most Rust programs this is as easy as doing the following on an Intel host
```
cargo build --release --target aarch64-apple-darwin
``` 

Although because Sheldon links to libssl this fails.

**Comment by mvgijssel** [comment]
Yeah would be cool if you can get this to work on the MacBook Pro m1 😍

**Comment by rossmacarthur** [comment]
The latest github runners are aarch64 so released binaries are `aarch64-apple-darwin` now
