### ISSUE TITLE
local plugin failed to find any files matching

### ISSUE THREAD

**Issue by gatspy** [rossmacarthur/sheldon#142]
the suffix of the local plugin file must be `.zsh` ?  
use `.sh` `.plugin` init error.

**Comment by rossmacarthur** [comment]
You can specify which files will be matched. Either using the `use` field on a plugin. Or adjusting the global `match` field. See the documentation here:

- https://sheldon.cli.rs/Configuration.html#use
- https://sheldon.cli.rs/Configuration.html#match
