### ISSUE TITLE
Library not loaded:

### ISSUE THREAD

**Issue by saladuit** [rossmacarthur/sheldon#151]
```
dyld: Library not loaded: /usr/local/opt/openssl@1.1/lib/libssl.1.1.dylib
  Referenced from: /Users/safoh/.local/bin/sheldon
  Reason: image not found
zsh: abort      sheldon
```

I'm using sheldon for two seperate systems, but it doesn't seem to be working on mac, at least not on the 42 mac. I'm unable to make ```
it myself due to limit space on my disk, which I can't increase as it is for all our systems. I've tried the:
curl --proto '=https' -fLsS https://rossmacarthur.github.io/install/crate.sh \
    | bash -s -- --repo rossmacarthur/sheldon --to ~/.local/bin
```
And downloading the binary directly. 
Surprisingly enough this time my Arch distro is running fine out of the box with the environment settings the same. 
Does anyone know a fix to this issue?

**Comment by rossmacarthur** [comment]
Thanks for the report. This might mean that binary built in CI is not fully static since its trying to dynamically load openssl 😞.


Are you able to install sheldon using Homebrew? They "bottle" it so it won't be built from source.
```
brew install sheldon
```

**Comment by saladuit** [comment]
I will retry, but one of the restrictions in this particular setup, is that my drive space is very limited

**Comment by saladuit** [comment]
==> ./configure --prefix=/Users/safoh/.brew/Cellar/curl/7.85.0 --with-ssl=/Users/safoh/.brew/opt/openssl@1.1 --without-ca-bundle --without-ca-path --with-ca-fallback --wi
==> make install
==> make install -C scripts
🍺  /Users/safoh/.brew/Cellar/curl/7.85.0: 504 files, 4.0MB, built in 1 minute 13 seconds
==> Installing sheldon
==> cargo install
==> Caveats
zsh completions have been installed to:
  /Users/safoh/.brew/share/zsh/site-functions
==> Summary
🍺  /Users/safoh/.brew/Cellar/sheldon/0.6.6: 10 files, 6.8MB, built in 2 minutes 1 second
==> Running `brew cleanup sheldon`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
==> Caveats
==> sheldon
zsh completions have been installed to:
  /Users/safoh/.brew/share/zsh/site-functions
f1r3s2% exec zsh

error: failed to load config file
  due to: failed to read from `/Users/safoh/.config/sheldon/plugins.toml`
  due to: No such file or directory (os error 2)
f1r3s2%

**Comment by saladuit** [comment]
works!
After installing the dependencies in two separate brew commands!

**Comment by saladuit** [comment]
I' didn't look through the issue yet. But I already see that It's quite a hassle to work around it, (or ugly). I'll just learn to live with it.
