### ISSUE TITLE
Depreciated config location warning even with environment variables

### ISSUE THREAD

**Issue by jltml** [rossmacarthur/sheldon#152]
Hello!

Firstly, thanks so much for making this awesome utility — it's been [around a year and a half since I had the luck of stumbling upon it](https://github.com/rossmacarthur/sheldon/issues/113#issuecomment-785965778) and I'm still just as enthusiastic about it now as I was then!

Secondly, it seems that every time I open a new shell window I'm still getting the warning about using the depreciated config file location even with the `SHELDON_CONFIG_DIR` and `SHELDON_DATA_DIR` environment variables set to `"$HOME/.sheldon"`. (I confirmed that they're set correctly by running `env`.) Is this intended behavior, or should the warning be silenced with the environment variables?

Thanks again!

**Comment by rossmacarthur** [comment]
This is not intended. Thanks for the report.

How are you setting the environment variables? You should set them in your `.bash_profile` or `.zprofile` or perhaps in your  `.bashrc` or `.zshrc`

**Comment by jltml** [comment]
Oh wait, this was really not smart of me — I had the environment variables in my `.zshrc` right *after* `eval "$(sheldon source)"`. I moved them before and it works perfectly now. Sorry, I don't know why I missed that at first!

Apologies for the erroneous issue and thanks again!
