### ISSUE TITLE
File mutex and no write access to config directory

### ISSUE THREAD

**Issue by rossmacarthur** [rossmacarthur/sheldon#159]
See here https://github.com/rossmacarthur/sheldon/issues/156#issuecomment-1316612221

It seems that when the config directory is not writable it causes sheldon to hang the shell.

**Comment by rossmacarthur** [comment]
@seqizz What permissions does your config directory and config file have? I'm strugging to replicate this.

**Comment by seqizz** [comment]
Due to nixos, it's a symlink, that might be confusing a bit:
```
~> echo $SHELDON_CONFIG_FILE
/etc/sheldon.toml
~> ls -la /etc/sheldon.toml
lrwxrwxrwx 1 root root 24 Nov 16 09:53 /etc/sheldon.toml -> /etc/static/sheldon.toml
~> ls -lad /etc
drwxr-xr-x 1 root root 1446 Nov 16 09:53 /etc/
~> ls -lad /etc/static
dr-xr-xr-x 1 root root 1280 Jan  1  1970 /etc/static/
```
But it reports waiting for lock on /etc, which my own user can not write to.

**Comment by seqizz** [comment]
Tested again, I think my original problem was different, I can't replicate this on 0.7.1 anymore :thinking: Thanks for digging though.. Not sure why it was reliably stuck on 0.7.1 back then.

**Comment by rossmacarthur** [comment]
Okay, then until something we can replicate happens, I'm going to close this issue
