### ISSUE TITLE
Feature: Nix flake support

### ISSUE THREAD

**Issue by jasonjckn** [rossmacarthur/sheldon#160]
add a flake.nix file to root of repo. 
I can write a PR for this if you want.

**Comment by rossmacarthur** [comment]
Happy to accept a PR for this :)

**Comment by jasonjckn** [comment]
looks like it was upstreamed into nixpkgs , i can still do a flake.nix if someone wants it, but probably not necessary

**Comment by jasonjckn** [comment]
oh actually they don't support aarch64 yet , so might still be worth it

**Comment by jasonjckn** [comment]
<img width="188" alt="image" src="https://github.com/rossmacarthur/sheldon/assets/550839/9d3e6854-cffd-49e6-9bf6-ba02a1de24fb">
https://search.nixos.org/packages?channel=23.05&show=sheldon&from=0&size=50&sort=relevance&type=packages&query=sheldon


So far no darwin support, so maybe this is still worth doing.
