### ISSUE TITLE
Dockerfile needs no confirm option

### ISSUE THREAD

**Issue by saladuit** [rossmacarthur/sheldon#163]
Hey guys,

love the plugin manager!

I was wondering whether it would be possible to incorporate a --no-confirm option for my Dockerfile. 
I'm not sure how to circumvent the following error.
<img width="399" alt="Screen Shot 2023-02-10 at 11 18 53 AM" src="https://user-images.githubusercontent.com/43225170/218066970-bb213eeb-a0a7-49c4-83d1-730509b0f4b9.png">

Any other suggestions or workarounds would also be greatly appreciated.

Thank you!

**Comment by rossmacarthur** [comment]
Fixed in 22b81e3a1a04fefa856cc9c187715bd0e2a2b95f. This will be available in the next release.

Usage:

```
sheldon --non-interactive init --shell zsh
```
