### ISSUE TITLE
Simplify error management

### ISSUE THREAD

**Issue by lovasoa** [rossmacarthur/sheldon#17]
Currently, this crate contains a single error type, defined as

```rust
struct Error {kind: ErrorKind, message: String, source: Option<Box<dyn _Error>>,}
``` 

And there is no automatic conversion from source error types to the crate's error type.

This is suboptimal (the error type is larger than it could be), and requires a lot of boilerplate code (currently there is one function per error type).

Error management could be simplified drastically by using a crate such as [custom_error](https://crates.io/crates/custom_error).

**Comment by rossmacarthur** [comment]
Hi @lovasoa thank you for your suggestion, in the past I have used [quick-error](https://crates.io/crates/quick-error), what are the benefits of using _custom_error_ over _quick-error_?

Could you also explain how the error type is larger than it should be?

The reason I didn't use _quick-error_ is that it forced me to use a different enum variant for each message.

**Comment by lovasoa** [comment]
Hello !

**quick-error** was a great crate, and you can still use it ! However, it was last released almost a year ago, and uses the now-deprecated `Error::cause` and `Error::description`. It is also a bit more verbose than [custom_error](https://crates.io/crates/custom_error) (a crate I authored).

>  Could you also explain how the error type is larger than it should be? The reason I didn't use quick-error is that it forced me to use a different enum variant for each message.

Having a different enum variant for each variant is what makes your error objects fit. If you have `n` errors in memory at the same time, and they all contain a String error message, than you use up `n` times the size of the String in memory, for nothing. If you use different enum variants, than you don't have all these duplicate strings in memory.

Defining an enum with many variants and implement `std::error::Error` for it is painful with the standard rust syntax, but *quick-error*, *custom_error*, or *error-chain* all define macros that make it easy.
