### ISSUE TITLE
how to install single plugins from ohmyzsh

### ISSUE THREAD

**Issue by shriharip** [rossmacarthur/sheldon#179]
Maybe error or issue related to submodule or something which I do not know properly. Would require support here.

I run the command 

`sheldon add taskwarriorplug --git https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/taskwarrior`

and it results in 

`error:` failed to install source `https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/taskwarrior`
  due to: failed to git clone `https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/taskwarrior`
  due to: unexpected http status code: 404; class=Http (34)

**Comment by rossmacarthur** [comment]
This doesn't work because the `--git` option expects a git repo but you are trying to add a link to file _inside_ a repo. You should do this instead:

```sh
sheldon add taskwarriorplug --github ohmyzsh/ohmyzsh --dir plugins/taskwarrior
```

**Comment by shriharip** [comment]
that helped and solved the issue.
