### ISSUE TITLE
Plugin update mechanism

### ISSUE THREAD

**Issue by rossmacarthur** [rossmacarthur/sheldon#61]
At the moment there is no way to automatically update Git sources to the latest, or to potentially periodically redownload certain remote sources.

It's still possible to update everything using `sheldon lock --reinstall` but that could take a while.

**Comment by alem0lars** [comment]
Are there some changes on that?

**Comment by rossmacarthur** [comment]
Not yet, although I haven't put that much thought into it. Any ideas on how to implement this would be appreciated 😄.

**Comment by dead10ck** [comment]
At least the case for git plugins seems straightforward, no? Navigate into the directory and do a git pull.

**Comment by rossmacarthur** [comment]
Yeah I think there is two main parts to this:
- Actually updating: this is the process of actually updating. This would be plugin type specific. If this is implemented first then it could be put in it's own CLI command.
- Automating _when_ to update: this would allow a configurable way to say "please update every 2 weeks" or something. This could be done on a per plugin basis, or a globally. Globally is probably easiest.

**Comment by alem0lars** [comment]
I agree with @rossmacarthur . Also it could be useful the possibility to check for plugin updates and notify user about that.

**Comment by rossmacarthur** [comment]
Resolved in 5a8254d36c73e79cf67782160cf63e9e6f5c3d9b

From version 0.5.3 you will be able to use the following to update all plugin sources and regenerate the lock file.

```
sheldon lock --update
```

I have created a new issue for automated updating #101
