### ISSUE TITLE
`lock --reinstall` deletes first and clones later

### ISSUE THREAD

**Issue by dead10ck** [rossmacarthur/sheldon#99]
It appears the `lock --reinstall` command will first delete all the existing directories, and then try to re-clone them:

https://github.com/rossmacarthur/sheldon/blob/master/src/lock.rs#L169-L176

This is unsafe, as cloning can fail, which will leave the user without any of their plugins. It should instead clone to a temporary directory, and then once everything is successful, then delete the existing directories and move the temporary ones into place.

**Comment by rossmacarthur** [comment]
Fixed in 7293cbf, this will be released in version 0.5.0 soon.

**Comment by dead10ck** [comment]
Awesome, thanks!
